field: 55861a05-5a37-4493-99d8-b2376473b946 # Slider One Matrix
fieldLayouts:
  533210ee-9c79-4031-a6ec-9e8040e22370:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b57e9701-0931-45a1-a545-29f7a2e4a2a5 # Info Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 531269ce-e429-4d3c-883e-ba776bcd13c2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abb58424-a7ba-44ae-8f21-160d31e05234 # Information
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0dc18801-f501-46ff-94e4-f7be55b042ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae39b74a-37a5-4bc5-b33f-ab9f35cfe627 # Info Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d6b23fe-f10d-4ff0-99fb-53adb0b471d5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 63cad3a2-841e-4c6b-afdf-4f423301e64a
        userCondition: null
fields:
  abb58424-a7ba-44ae-8f21-160d31e05234: # Information
    columnSuffix: efdtqedg
    contentColumnType: text
    fieldGroup: null
    handle: information
    instructions: null
    name: Information
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4cf4cf0-9fac-4d90-a42f-2bdb6eb23e8f # Just Paragrpah
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  ae39b74a-37a5-4bc5-b33f-ab9f35cfe627: # Info Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: infoImage
    instructions: null
    name: 'Info Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b57e9701-0931-45a1-a545-29f7a2e4a2a5: # Info Title
    columnSuffix: vqjznnbx
    contentColumnType: text
    fieldGroup: null
    handle: infoTitle
    instructions: null
    name: 'Info Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: informationPoints
name: 'Information Points'
sortOrder: 1
