field: a1fba123-040e-4eae-8808-589c81511e3a # External Button Matrix
fieldLayouts:
  0b7c72f9-c8e8-477b-8f01-3e5c289f5409:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b2f8cca-63bd-4a4d-a08f-a5f0df8881d9 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 274997d6-1ed3-4ba0-9028-7093e659e5e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37057673-0304-4a8f-8fbb-d7bbb6427154 # Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19ae476a-004f-48fd-a448-c0068cf1185b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f7ea502-b762-4eb1-a5f6-0ce7a2570726
        userCondition: null
fields:
  4b2f8cca-63bd-4a4d-a08f-a5f0df8881d9: # Button Text
    columnSuffix: nldjtbxa
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  37057673-0304-4a8f-8fbb-d7bbb6427154: # Button Link
    columnSuffix: tsautfzn
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonLink
    instructions: null
    name: 'Button Link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: informationPoints
name: 'Information Points'
sortOrder: 1
