field: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
fieldLayouts:
  3a09f984-0ff5-479e-9c82-40ef0539347c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8d9a31ba-d65e-493b-9959-8e5325e6a347 # Style Two Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8787f6eb-3dee-48cc-9fb4-5ad5cb559168
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ee0aae4-fbcb-47a2-b227-8e1dee4b186b # Style Two Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 732d80e6-b00f-4bd2-bc57-0984a2a053af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e70e3f4c-23b4-4dfd-9ba0-c0d7a0ec3886 # Style Two Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68a5c52c-d459-4487-aed9-e8d43990e387
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 01ada6c2-be55-4a8d-91ec-5ecd5b108b90 # Style Two Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5306b93a-c96f-45c1-8e20-11e0088842bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49d813de-a352-4603-b185-eb0db3d87c25 # Style Two BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca2b485f-c8d7-4680-982d-4f15a71b0cb2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c9ca0789-fdeb-47c4-8087-8bdecfef6c19
        userCondition: null
fields:
  01ada6c2-be55-4a8d-91ec-5ecd5b108b90: # Style Two Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: styleTwoImage
    instructions: null
    name: 'Style Two Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6ee0aae4-fbcb-47a2-b227-8e1dee4b186b: # Style Two Text Bold
    columnSuffix: hgkdbusv
    contentColumnType: text
    fieldGroup: null
    handle: styleTwoTextBold
    instructions: null
    name: 'Style Two Text Bold'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4cf4cf0-9fac-4d90-a42f-2bdb6eb23e8f # Just Paragrpah
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  8d9a31ba-d65e-493b-9959-8e5325e6a347: # Style Two Title
    columnSuffix: pmhrcigs
    contentColumnType: text
    fieldGroup: null
    handle: styleTwoTitle
    instructions: null
    name: 'Style Two Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  49d813de-a352-4603-b185-eb0db3d87c25: # Style Two BG Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: styleTwoBgImage
    instructions: null
    name: 'Style Two BG Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:e17d1087-9a94-4873-a162-18d74f187ea1' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e70e3f4c-23b4-4dfd-9ba0-c0d7a0ec3886: # Style Two Text
    columnSuffix: yqvwffhn
    contentColumnType: text
    fieldGroup: null
    handle: styleTwoText
    instructions: null
    name: 'Style Two Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: e4cf4cf0-9fac-4d90-a42f-2bdb6eb23e8f # Just Paragrpah
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: styleTwoGroup
name: 'Style Two group'
sortOrder: 1
