app: gentle-dental
ssh_url: gentle-dental@deploy.eu2.frbit.com
git_remote: gentle-dental/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
