app: gentledental
ssh_url: gentledental@deploy.eu2.frbit.com
git_remote: gentledental/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
