fieldLayouts:
  6a783aed-9bdb-4d79-9092-9846949ba891:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9a7a3532-9294-4654-b77f-f4756a08dc1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 176d8966-ef99-423a-96b3-307f0683be40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 22b99db3-b0ca-449b-a678-7d173a1be769
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aed82994-f2b2-4597-84aa-5ecb05186fe3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05a00086-bbdf-47d7-81e4-275df4b57a76
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe26171e-cb2f-4dcb-864c-f66aaccecf48
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bbab2e6-2160-4c6d-8ffa-b741a79bd898
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ec69710-0ce1-46d9-adad-aa3e5ab7ed7d
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: c496a511-d1e1-419a-8d9c-553f404720bf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1581456-29fd-4801-9e2e-2ac599d703d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 866f883a-1ec9-4ff7-a47d-2397845503e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4344e13-9816-4aef-a2c8-ef5ce956e355
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 400a62cf-5dd2-41b7-81f3-c4815a00f123
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: a4ab5c3a-33e7-4afd-ae9a-e494b65ab914
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e585d9f-5f51-4a6b-ac4a-6ad650b0d608
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 745f1ade-372c-4650-8969-8fbea90ff3ba
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1371f0fc-6247-4162-bba3-3dbb67b4bd70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d199612-68da-4dc7-b52f-beb7a567ab2b # Style Four Text 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8632855c-8a53-4b58-ac4e-d4f5aff4e657
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: 73072420-f045-4ef3-8f04-1d50c5da4e33
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f64336a-15d6-4315-bb26-907253f95a71
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b5bfeb4-332c-4c81-ad0d-f9d24a8db607
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef65059b-7e5e-41f1-b380-57f5001d423b
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 92381359-f177-43dd-982a-246924d0585e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fbedacb-a189-428d-aaa7-2d6242ec26fb
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: 9b1aef6c-8cee-443b-8172-684a056a24a1
        userCondition: null
handle: cosmeticDentistry
hasTitleField: false
name: 'Cosmetic Dentistry'
section: 453d4f2d-1ca5-455a-adbb-78369ad20816 # Cosmetic Dentistry
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
