fieldLayouts:
  86cad63b-1361-4fa1-9d50-a3a5cf8d8ded:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: 'FAQ Question'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3bed61ed-24a3-4a3f-a9ea-1ee0814809db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c60c910-8f6b-4153-8c35-b01931f85d58 # FAQ answer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0004cad-051f-42a5-987b-82bd61e0e335
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8d36149-abd4-4caa-ad1b-422329ad1e15
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 76ed36c0-3eb8-41f4-91dc-0d4012c2f0c7 # FAQ Exam and X-ray
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
