fieldLayouts:
  03027e31-7472-4939-832e-3f3cf5745113:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa6f1426-9f9a-4d66-8620-a6f6c5f04da9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e801c0a5-9ed2-4394-9f9c-4ad29614d7be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5028f55-ffb6-4d96-8fef-7840a069f5d9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7623827-f363-444f-b7b3-393690e41f9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89921fdc-6476-45fc-8536-2865097669fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95ab0537-c8ab-42c4-a3c3-dd4b55f59a0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 100e8239-76b7-4250-aa23-9a69741420f5
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: f2cb1f86-bd40-4a10-a80f-60a8cef2f652
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c58921ea-009e-464e-9bd2-80b6cf4a7cfb
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 5ad8b6c7-0685-43ca-9163-5f4de88a7d46
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56489242-d549-45bc-ac3f-5e7b8573d7f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d199612-68da-4dc7-b52f-beb7a567ab2b # Style Four Text 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df523a31-00f6-43c5-ae34-810143db428b
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: 6fd0121f-0031-485e-ac73-a7f539cbef63
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2c628d2-6aff-45c8-8c2a-df9e6594e53e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b584f99f-7a2d-43a6-aa34-0dd2d58cac32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7146fc3-6679-4977-b91b-f17cdf92e371
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a77a729f-b69c-4df6-99e9-6c1287886132
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 46396c76-aa34-4e79-9673-4fece31ad51d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b80c873b-b691-4223-b1a0-960bd435a5fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a4d7ae4-17da-495c-a443-25190fc6e055
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e530c2b-1c3f-47aa-8b6a-20b44657d86f
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 5a5b77cf-b827-4f5f-a426-51fc7245c510
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ef8a677-53cc-47ba-b64c-528d500210ad
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: ee374b41-6535-47fa-a8e3-91d07714908f
        userCondition: null
handle: dentalImplants
hasTitleField: true
name: 'Dental Implants'
section: 6dc51202-5dd8-4f99-8384-a017bb20cefe # Dental Implants
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
