fieldLayouts:
  d1306503-4c49-4fd0-b3c7-b3d0feb8e651:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cedd305c-08c2-44f2-bd8c-5d3a425e0627
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62716344-0f8b-4ce2-861c-db2136fd250b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edeedffd-e74b-4ec2-9a04-821f6f2eba1f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28b8e46c-5a3b-4657-8670-ef4eef001249
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72b8c5b6-300e-418c-803b-2b7541c5df42
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ef1da78-1a89-45d7-982d-d4fd3b78a37a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3371d101-66c1-4e6e-a7ed-88c83b7d0da4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d938e9fa-b336-4aa9-863d-450b993d9ac3
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: f7dc3aa0-b8e2-4ffe-b25e-789748bfc2a8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca5a56a9-9c6b-4eca-9542-b5cd8122d8b7
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 8adea2d8-a660-4985-92a0-5279d52689c0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e7ab8b9-c939-470e-a7a1-855076a0f538
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdc20443-fd87-4348-b5c9-1b3010b3b169
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2495b00-46bd-4217-bd51-189d8944e3cc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4ad5869-91e1-4244-a38d-dfef695bc906
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 6c513882-5e95-4454-a16c-e0d0349d3faa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf13cd02-71f2-4d32-a519-990d4cd6256e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d199612-68da-4dc7-b52f-beb7a567ab2b # Style Four Text 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe068e53-ae03-4d9a-bba1-083dc0e4be80
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: f200add6-a5be-41f4-9645-5941f1423ba5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84bda165-0578-409e-aaf7-576222aba62a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 02e7b626-26d5-45b5-9ef7-7db04138226f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6525e38-7edb-48b3-a21b-abd23e33c91c
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 5af99240-d711-4083-884c-8e8354af21fc
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4caad0b2-152c-48c2-a97a-91d9f3a5bf1d
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: 3fb87f9b-93c2-4523-9199-68c0b5bb3b35
        userCondition: null
handle: dentalCrowns
hasTitleField: false
name: 'Dental Crowns'
section: 1856c310-64df-4909-811b-e5626d7f5d53 # Dental Crowns
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
