fieldLayouts:
  43a315f3-25d1-4748-bb04-3f3d15c6717e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7db341be-da29-4087-b78b-1bfb3a9b98b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0637e067-fa31-4139-bacb-aea912f4d520
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5d574cc-f9a0-4836-8f8d-3888eed8359b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49d7c357-e84a-4bee-8d21-e50bb0a49d49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ea13a9a-ae2e-49b1-8076-a636c23bd4c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6353ca4d-4962-411b-ac17-3dc22c1b1684
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5901a1a-8359-4084-8b2b-83deb67f0fba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28d986ac-d0de-4643-9707-6612d5e7b4e5
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: 4a9c02f4-3ef1-481f-9224-aa2cda410d92
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac2de254-74f3-4e52-bc87-071b5dd1ada7 # Slider One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a689b49-871a-4d62-b21c-30d5db41050a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec8a45bb-4f7d-4a01-8337-0a7a37fff2c1 # Slider One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9d85af0-1fd9-4a74-8c87-5193b3950108
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c183bb56-42dd-4a59-b70b-0d40b9d2a72f # Slider Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f636093-55ac-4e96-98d7-b18d6df82431
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 4641f155-97d8-427b-af80-fb64dcbb2ba6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f709e1c-757c-4056-b51b-69cfb5ed9285
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d4d5ab6-68c1-41c9-82ac-26f61727304a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11ed2c61-b483-469c-8438-6d3ea55673db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b4cbb0e-e833-4fb7-8cf7-75a144994208
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 14e1e88f-9c05-42c5-ab09-0da5b4144736
        userCondition: null
handle: digitalDentistry
hasTitleField: true
name: 'Digital Dentistry'
section: d556265d-fbd8-48ff-af0b-a118334febe3 # Digital Dentistry
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
