fieldLayouts:
  6209e26a-9789-4b42-9d48-e5c6b01ebbd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7995c6c4-fb28-4ff1-86f0-318dc7b8573c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64cf07ab-117d-499c-a99e-8fbe56fcc212
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93c23aa6-5df1-4ca9-b1a1-b6d03dca326c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c975e51-4777-4321-be43-4b6591c47126
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 128c5421-848f-4dcd-b5b3-be4869a8b26f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fbed35aa-3f67-4b32-b7ee-d3bf1b4971a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a52d5bbf-1f8d-4a81-a5ed-ed93ced8a6a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 728052cb-09d9-4e62-94c7-1db7a40582a6
            userCondition: null
            warning: null
            width: 100
        name: 'Style One'
        uid: 95eb8f07-fab3-4330-be93-84375a6489e5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 92e9e500-a726-428b-8780-044725bba4fa
            userCondition: null
            warning: null
            width: 100
        name: 'Style Two'
        uid: d5ddde10-32b1-4a2e-aaf2-9ec68abbdbae
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20581d55-0c68-4c8f-a9e2-e0ce99c3eaa8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20579fcf-1ab0-48cf-a4fd-06278939fcb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f310013-a59d-468c-9d25-857f67c74e9e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16d81648-ee91-4075-b298-4d880d2c858e
            userCondition: null
            warning: null
            width: 100
        name: 'Style Three'
        uid: 5741444a-d698-4f97-826f-8e3e8db662c5
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c42dc058-b6b4-4268-b8bc-59ca704a9cdc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d199612-68da-4dc7-b52f-beb7a567ab2b # Style Four Text 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e5fa78f-4f2a-4ad0-b1d1-ffba2531e609
            userCondition: null
            warning: null
            width: 100
        name: 'Style Four'
        uid: 18c6fe1e-3803-4a42-a810-1cc6acb3b968
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bfc55fb-a651-4179-a7bd-ef262f4eac2c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4364a6bc-0b4a-4c8e-a3a6-5e305bd1b617
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f02c7471-7819-4d26-8e1f-0438572d5466
            userCondition: null
            warning: null
            width: 100
        name: 'Style 5'
        uid: cbdd9f80-d7fc-408a-9b12-eb878dc25727
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e3bd000-7e54-49d5-a864-c2764cd96af1
            userCondition: null
            warning: null
            width: 100
        name: FAQs
        uid: 05d3602a-09e0-4252-8701-2bfd8010be08
        userCondition: null
handle: examXray
hasTitleField: false
name: 'Exam & X-ray'
section: 4503af49-dbfd-44e2-b013-c487224ab8b9 # Exam & X-ray
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
