fieldLayouts:
  2b097c7b-4974-4233-9c60-d22b67703f02:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ffb92142-55a1-4ea7-891f-fdeb2396e794
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34ba00d0-e221-4c3d-9cb1-a915bb45b531
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 34c2bf06-6010-40d0-9df4-2da2d35529c4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c35cf04-8464-4858-911a-c7e858fafe26
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b155ccb-4742-4716-942d-bcc2a98887ea
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7af4b67-56da-4c8b-a04e-12264e2fe0c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2de7574-eb8d-4203-8064-6c3941a39860
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: 82fb7d41-e9e9-4e76-a0ea-2e663938efc7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5e9fd30-c991-4658-80b4-9ce34209f9f1
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 406a74a0-bf4c-4fe7-be13-03da951dc9bf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d1d7575-a60d-48c6-bdbe-80c379658af8 # Style Seven title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3dc262b-4554-4b00-9613-663c12102160
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ba9f6e6-56ec-4f5a-9c3f-e7654139bd14 # Style Seven matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47f6fd7f-5ba5-4b03-be16-95eaee35f84e
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 9f0050d3-8e25-40ec-9c6c-28178f7331c1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac2de254-74f3-4e52-bc87-071b5dd1ada7 # Slider One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a616144f-74e3-459e-895e-4381ae37ca49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec8a45bb-4f7d-4a01-8337-0a7a37fff2c1 # Slider One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 554d6c14-dd1c-44b2-a38c-337e44ba8ccd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55861a05-5a37-4493-99d8-b2376473b946 # Slider One Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43aab68c-d0b3-4990-ac8c-2b67cc25caf3
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: 29dec7fe-6599-4ddf-bacb-6856d74c6631
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50b25310-1504-4a4c-961b-a9a6fec85387
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be9dc213-7ad7-441b-ab72-9f92aeb364b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 07d42d69-2bb9-41cb-8106-26103b1b1b80
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 3a7a3a44-7c89-4a42-a481-3fae3b51af41
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 272ff1cf-4a84-4a88-8926-832f7c81c78b
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: 7e734192-1673-4cdc-8daf-9278aa2c41ce
        userCondition: null
handle: gentleBraces
hasTitleField: false
name: 'Gentle Braces'
section: ec2cf642-4d80-444f-aaa9-a16e2ed8aa24 # Gentle Braces
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
