fieldLayouts:
  f5a8b86e-954c-4f1a-b990-c7f1e47b279e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e900ce1-4ed2-4277-a457-c3152175196a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a0e55e82-b6b8-41bf-8bac-86ace2e598d3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac36c670-2132-4b8d-8187-bcc4377437b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58e8ee1c-9679-4075-98f7-0c820a2b825b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0156f273-537f-4c64-bd66-3c0b3c80dea0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91dc1195-600b-4a40-b6fd-430d500b12b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a17efc87-22f6-417a-af90-6ef1bbce5bed
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: 9313976c-0cb3-4b1a-882e-3fa61dd4c498
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d1d7575-a60d-48c6-bdbe-80c379658af8 # Style Seven title
            instructions: null
            label: 'Style Two Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8671114d-e265-47fb-89bf-debfef64dfba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9440fb59-9a0c-4447-99cc-7650bc984f49 # WTE Other Text
            instructions: null
            label: 'Style Two Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f3d17c3-4923-4eb8-8c61-33751df534b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ba9f6e6-56ec-4f5a-9c3f-e7654139bd14 # Style Seven matrix
            instructions: null
            label: 'Style Two Information'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a8b76a9-c085-48fe-a0ee-15c53c9ee860
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 8a5d8aaf-b0b4-475f-89f6-7a631087da98
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ef57d1b3-6c83-4a76-aeca-460bf8d591ea # Style Six Title
            instructions: null
            label: 'Style Three Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d4fa475-6d02-4f7a-b3af-28c8b2100d0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1efd98b6-0a32-41cf-8c3e-0b6cf7e61985 # Style Six Text Bold
            instructions: null
            label: 'Style Three Text Bold'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ed73a42-6741-4be9-96e6-7deb88c54617
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 47434d50-7052-4bd6-ba93-3fcf9e79eb9a # Style Six Text
            instructions: null
            label: 'Style Three Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38855e65-ff4d-4787-b0c7-a615e4e61905
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b2a91915-e231-478c-a98b-785b01ed7563 # Style Six Image
            instructions: null
            label: 'Style Three Small Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03676ff8-ba9b-47f3-8205-c772bd5975ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: 'Style Three Image Banner'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1adaa00-6d0c-4e9b-8b4a-6c3431eb3f22
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 1622fc12-5f12-483b-90a5-b894d87a1501
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac2de254-74f3-4e52-bc87-071b5dd1ada7 # Slider One Title
            instructions: null
            label: 'Slider Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab22f029-08ca-460f-af34-1e74821cab1c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ec8a45bb-4f7d-4a01-8337-0a7a37fff2c1 # Slider One Image
            instructions: null
            label: 'Slider Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 408dd54a-516a-4058-9090-ee9ab359eb62
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c183bb56-42dd-4a59-b70b-0d40b9d2a72f # Slider Two Matrix
            instructions: null
            label: 'Slider Content'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2106bf4f-9b96-40c0-a087-6057a7b04de0
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: 54230137-886b-49c9-aef5-f3a7a257e8b9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: 'Testimonial Section Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d04bee36-3a9a-4ab5-83af-5f86fa809259
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a6935e00-3863-47c8-b7c9-9406f726a4d5 # Testimonials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69fb1b3d-4893-49c9-968d-0ee8cd1acb75
            userCondition: null
            warning: null
            width: 100
        name: 'Testimonial Slider'
        uid: 6e6e306f-5ab4-43d0-89f0-b98d045734e9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53e77d06-163d-4658-88fb-05be3873089b # General Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ffdf898-4562-48a1-b08d-27107848a815
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c69928ed-19bc-4644-aa8d-1e98785c6de0 # General Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ac849d5-4557-45e1-84ec-a780e11ab217
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2184b1b9-24d8-494b-9f2a-04e18970a142 # General Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9a47c65-b8dd-4fdb-b346-c19f73a1e494
            userCondition: null
            warning: null
            width: 100
        name: 'Contact Intro'
        uid: 825a9a4e-6581-49bc-a547-3359400b8b61
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: 0fab3bf0-6361-445a-b238-c15ed8c4f5f8 # Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
