fieldLayouts:
  7562c1cf-d7ec-436f-9544-eb7fea2dc828:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b21c651c-c5d5-471b-896a-106ec40f6705
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 11af7000-8557-4730-8ebf-b3f907490c8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4040ee2a-901c-4981-b2f9-33c80d07674b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba141200-0d22-4907-8ea0-d14b3cf77b09
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca38df44-4b74-451d-b7c7-c7d3b4c13273
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36917794-dfe4-48be-8e35-53949dd1ff74
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 397ff6a6-294a-4829-b2bc-8538281d01ae
            userCondition: null
            warning: null
            width: 100
        name: 'Style One'
        uid: 6676b5c7-4f9d-4bea-b9dc-8c44dc11a22e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d026f356-7b53-4be7-ac08-a23b6291ed51
            userCondition: null
            warning: null
            width: 100
        name: 'Style Two'
        uid: 842016a4-d232-44b0-bb7a-c3c14251950d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ba182cb-96a1-40fb-901d-5c2791907e3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9b4751e-e7c5-4a67-8cb9-086af0b7fd8a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c8492cc-8674-43d6-9a06-d80d900095aa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 957d20bb-2085-467b-a6d8-1dea36413177
            userCondition: null
            warning: null
            width: 100
        name: 'STyle Three'
        uid: 4d170b59-68fb-4bde-8fa0-e536a3403324
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a4e6d74d-d154-4eeb-9700-cb668d206f43 # Style Four title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0a55a92-493c-4ed6-9f65-25e9dc92f7c4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5d199612-68da-4dc7-b52f-beb7a567ab2b # Style Four Text 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13ee9c2c-adfe-48b0-a58d-fd6f974807d7
            userCondition: null
            warning: null
            width: 100
        name: 'Style Four'
        uid: b3ea86bb-acc3-4db4-8ea3-bf6923fc5f2f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aaca3a75-aa2c-468e-a9ee-21690f7e4af2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0db7cfd4-fe57-496b-b8cb-bfd125140c0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 864e5d3b-e9bb-4cac-8115-7ccf054ef86c
            userCondition: null
            warning: null
            width: 100
        name: 'Style Five'
        uid: 53dabd70-e9db-4569-8e3f-21134e8d6a7d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d46675a-4ba3-4adf-8ea1-d8d8e041f151
            userCondition: null
            warning: null
            width: 100
        name: Faqs
        uid: d3e47783-b16e-482d-92c5-d446fb79a215
        userCondition: null
handle: hygieneTreatment
hasTitleField: false
name: 'Hygiene Treatment '
section: 99e67643-418f-426c-8878-bdaf710cbec4 # Hygiene Treatment 
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
