fieldLayouts:
  e00e196c-848a-41dc-998a-7e8d6ef4a70d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2c4917fc-132b-4b79-8db6-63598cc4ff2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 06d253c9-ee4e-4946-a70e-267fe8eb983b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0131f0df-f88f-4d86-afd7-7fb14f13cd7e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7496b38f-aa5a-4c2d-83e3-f97bff7d0f02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd83bdd8-9e3e-4b44-a86a-60cd41dc485c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f5ed21e-e085-4d98-89df-3e1b7f92a270
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49b61012-0f0c-465b-aa21-6de41c096b5a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18bb7818-5d5d-48f3-912d-3f6598c13d0d
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: b06dd20a-38dd-4468-a634-17b338aeea98
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0efe02ab-b1a2-40d7-8bc0-77c2051b4d3e
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 0837a460-6df1-4dd1-8a29-85c78c23bb5e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0d1d7575-a60d-48c6-bdbe-80c379658af8 # Style Seven title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bcbc8d6-c9ed-4fef-8bbd-78f125b570a3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7ba9f6e6-56ec-4f5a-9c3f-e7654139bd14 # Style Seven matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c8dcbd9-e775-4f46-a488-8f46b0f5f3fe
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: bc9d0a3a-7f24-4101-bc48-9929524356c9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a76dbe-dcc8-40e1-bf62-860e08a9795b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0cd24711-366d-42b3-9ec5-364a43acb0b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df1c558d-f3d9-4a8a-a403-c0f7c0069b27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d0c9f8f-abb5-4e5c-ad81-4bb757236944
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: cccf26b5-e1c1-469d-a33a-6ac8ac596542
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10c4974a-e8d2-4868-a4b0-610eb70b7da4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 586b0c30-ec3c-40b1-ae6e-78eaf206d65c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13f0e7e7-3196-4c86-ad80-7c669821d195
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 3d2327eb-3f5b-45a4-b1b9-ed6d15b2ba90
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aebea575-00b4-4a4a-b010-fd78e702bd5b
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: 5980ec26-c1a5-4adb-8c83-91eb31e550c7
        userCondition: null
handle: invisalign
hasTitleField: false
name: Invisalign
section: 4a7a0920-a2cb-4432-be51-afefad05a771 # Invisalign
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
