fieldLayouts:
  4a12c6d6-27b5-421e-b5a4-742ebd2fce20:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b21b568f-e0d1-41d3-85f4-e68aea465b61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b909d020-c84e-45d3-b79b-13d279b449dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8ac08172-6427-4aec-b3c2-7140ec62ada7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1319c391-eb94-41e5-901b-9ab2db7d9ff0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa80b505-eeeb-4fbc-bc63-7c7a4c6d341a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d94f9449-cadd-4cb1-b3e0-ad7d7626d619
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8d13bba-dedf-49c4-ba8f-9dc9401cba05
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ec9897a-4a99-4f5e-97ae-4a66c0d3f3b7
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: 540b8d41-fb0d-4a3c-9633-600eae30d3f3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cac7c5f-4f60-4442-953c-a9c494727735
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 67f2dcfc-6e56-4063-80ae-2844bdd3b444
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: 'Style Four Title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5aa4729b-befe-43be-a3bd-d095917fa88e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: 'Style Four Text Bold'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c5cc3e1-0944-4f65-887d-c14d13245d87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: 'Style Four Text'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcef070f-1b01-4a95-9c91-0ba06bff825a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: 'Style Four Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f77f9d46-9a82-4f38-8413-bcb3f71acdb8
            userCondition: null
            warning: null
            width: 100
        name: Four
        uid: b38ddf86-c54c-4acf-a8d5-156948d3792d
        userCondition: null
handle: ivSedation
hasTitleField: false
name: 'IV Sedation '
section: 9e13c565-0c39-4311-9482-c7fd2e9687c5 # IV Sedation 
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
