fieldLayouts:
  d43405f0-042b-402c-8ab0-8943b765d5a5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f760af8b-c66b-49ba-8902-964a47a3dc2a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5728dc45-e52d-4e41-a8c9-4082b7247811
        userCondition: null
handle: other
hasTitleField: false
name: other
section: 57989829-02c2-4417-b994-0a51afbfd3e5 # other
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
