fieldLayouts:
  bf09fe12-fe8d-4bbd-b96b-6da343421d9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 761ac636-e368-402c-9f77-e7d35c7975d4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90c9b16f-c7c3-4dd9-96ca-aa26cf907067 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fdb7766-ad54-4417-b298-b5eac867016a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbac6ea1-5e29-46c2-affd-0c27b956c5a6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e82dbb37-5c20-480c-9edb-c8cb30603cb8 # Style One Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ed09c2c-9586-445d-bb78-5586782e6c50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f0fc869-abab-4809-83cb-4804013ac713 # Style One Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f003af64-a74a-4416-9851-7666e91ee8fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9f6531ad-88af-4137-99a6-15a7b7a9dd51 # Style One Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00fa4d3b-c369-4638-b82c-b51f90f8a9a4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e002b8b3-446b-45ca-8eb2-38ef159e9919 # Style One BG Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7260513f-e2cd-4411-8932-f9499706d9da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 481b4eaa-6d7c-45b1-b40d-69cafd4d3004 # General Button Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6d1ae96-c677-4cda-84e1-ecf143a5423c
            userCondition: null
            warning: null
            width: 100
        name: One
        uid: 55a48a91-36b8-478a-901e-5953f0e210be
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ec565f82-1fc1-404f-a28c-8534ba0fe1f6 # Style Two Matrix
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f96442c-87a4-4487-a0c2-01b1cd07c18b
            userCondition: null
            warning: null
            width: 100
        name: Two
        uid: 28827fe2-f8f3-4be0-a5ac-4bd30a465254
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f89c1aa7-8c8e-44f6-a609-1c87f95d517a # Style Three Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94e56166-54d8-4e0b-bcca-a9ba439584e8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3a233f41-129b-482b-82c0-b37d9513508d # Style Three Text Bold
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7087a58e-78b4-4d4a-8b2d-07c50252a912
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7f05bf0-5592-428f-ae47-3a27c9f7cf39 # Style Three Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58f654cb-d238-4004-8540-c7816a868fb5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c68f10b-f403-4152-bf72-efc2d896cf4e # Style Three Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8a78077-f4c2-446e-939d-33f0c1880cce
            userCondition: null
            warning: null
            width: 100
        name: Three
        uid: 680af978-4327-48b6-b531-d8f5a67b6790
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9c8f2362-5366-49fe-aa97-9bffefe2770a # What to Expect Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e38f465-664a-4446-ad2e-533777af4c7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77d908c2-264d-4aff-9094-d72feb9be2ad # What to expect image 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c308e9a6-1fc3-472a-b1e1-550a7e8dc8fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 404bd0ae-9bda-40d1-9caa-bd3084d4579b # What to expect
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 38a2e821-1f80-44ce-a6c0-9f181f96ab3d
            userCondition: null
            warning: null
            width: 100
        name: Five
        uid: 509c204b-17e9-453a-9a7a-06ec488c4c10
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e9fddc4a-fb16-4c1c-afc2-3807def662a8 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f5fbaa8-0613-4115-ade8-0505e8d2f503
            userCondition: null
            warning: null
            width: 100
        name: FAQ
        uid: bf57905d-d966-4680-adb8-b03859590f40
        userCondition: null
handle: teethWhitening
hasTitleField: false
name: 'Teeth Whitening'
section: 678567e8-7ba0-4a2c-8f98-5e1811aff168 # Teeth Whitening
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
