columnSuffix: rdzbocps
contentColumnType: text
fieldGroup: 023e5938-6808-4ed5-99cb-3bfd69fb6f3d # FAQS
handle: faqAnswer
instructions: null
name: 'FAQ answer'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 6559a804-b843-4bb6-bca5-e1ec814c419e # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
