columnSuffix: giovtwri
contentColumnType: text
fieldGroup: 023e5938-6808-4ed5-99cb-3bfd69fb6f3d # FAQS
handle: faqTitle
instructions: null
name: 'FAQ Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
