columnSuffix: null
contentColumnType: string
fieldGroup: d89ae37b-0b78-4516-9204-5f3145b063d4 # Services Pages
handle: styleSevenMatrix
instructions: null
name: 'Style Seven matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_stylesevenmatrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
