columnSuffix: null
contentColumnType: string
fieldGroup: d89ae37b-0b78-4516-9204-5f3145b063d4 # Services Pages
handle: wteOtherMatrix
instructions: null
name: 'WTE Other Matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_wteothermatrix}}'
  maxBlocks: 6
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
