fieldLayouts:
  266c555b-f9bb-4d11-a19b-95b7451e33bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32c7d1f0-b971-4de2-b8d0-d501f8c8ff25 # Common Image One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5ee1dfa-bcd9-4b00-b4eb-1c7e3f14fdd0
            userCondition: null
            warning: null
            width: 100
        name: 'Footer Image'
        uid: ad79a9d5-4c5d-408c-8bf1-dc9f4ff121f0
        userCondition: null
handle: footerImage
name: 'Footer Image'
sortOrder: 3
