fieldLayouts:
  ee646afa-eda5-48fd-a49f-f86bf3889646:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32c7d1f0-b971-4de2-b8d0-d501f8c8ff25 # Common Image One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c2a9d18-6e8b-4fa6-8a62-2f8fb7e66a02
            userCondition: null
            warning: null
            width: 100
        name: Logo
        uid: 3be9ba76-fd92-4d4c-8e66-798f11ef9271
        userCondition: null
handle: logo
name: Logo
sortOrder: 4
