defaultPlacement: end
enableVersioning: true
handle: aboutUs
name: 'About Us'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/about-us.twig
    uriFormat: about-us
type: single
