defaultPlacement: end
enableVersioning: true
handle: amalgamRemoval
name: 'Amalgam Removal'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/amalgam-removal.twig
    uriFormat: amalgam-removal
type: single
