defaultPlacement: end
enableVersioning: true
handle: childrensDentistry
name: 'Children’s dentistry'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/childrens-dentistry.twig
    uriFormat: childrens-dentistry
type: single
