defaultPlacement: end
enableVersioning: true
handle: cosmeticDentistry
name: 'Cosmetic Dentistry'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/cosmetic-dentistry.twig
    uriFormat: cosmetic-dentistry
type: single
