defaultPlacement: end
enableVersioning: true
handle: dentalCrowns
name: 'Dental Crowns'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/dental-crowns.twig
    uriFormat: dental-crowns
type: single
