defaultPlacement: end
enableVersioning: true
handle: dentalImplants
name: 'Dental Implants'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/dental-implants.twig
    uriFormat: dental-implants
type: single
