defaultPlacement: end
enableVersioning: true
handle: dentalBridges
name: 'Dental Bridges'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/dental-bridges.twig
    uriFormat: dental-bridges
type: single
