defaultPlacement: end
enableVersioning: true
handle: dentures
name: Dentures
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/dentures.twig
    uriFormat: dentures
type: single
