defaultPlacement: end
enableVersioning: true
handle: emergencyDentist
name: 'Emergency Dentist'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/emergency-dentist.twig
    uriFormat: emergency-dentist
type: single
