defaultPlacement: end
enableVersioning: true
handle: extractionsWisdomTeeth
name: 'Extractions & Wisdom Teeth'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/extractions-wisdom-teeth.twig
    uriFormat: extractions-wisdom-teeth
type: single
