defaultPlacement: end
enableVersioning: true
handle: faqExamXRay
name: 'FAQ Exam and X-ray'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: faq-exam-and-x-ray/_entry
    uriFormat: 'faq-exam-and-x-ray/{slug}'
type: channel
