defaultPlacement: end
enableVersioning: true
handle: fillings
name: Fillings
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/fillings.twig
    uriFormat: fillings
type: single
