defaultPlacement: end
enableVersioning: true
handle: home
name: home
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/home.twig
    uriFormat: __home__
type: single
