defaultPlacement: end
enableVersioning: true
handle: hygieneTreatment
name: 'Hygiene Treatment '
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/hygiene-treatment.twig
    uriFormat: hygiene-treatment
type: single
