defaultPlacement: end
enableVersioning: true
handle: invisalign
name: Invisalign
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/invisalign.twig
    uriFormat: invisalign
type: single
