defaultPlacement: end
enableVersioning: true
handle: ivSedation
name: 'IV Sedation '
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/iv-sedation.twig
    uriFormat: iv-sedation
type: single
