defaultPlacement: end
enableVersioning: true
handle: oralHealthTips
name: 'Oral Health Tips '
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/oral-health-tips.twig
    uriFormat: oral-health-tips
type: single
