defaultPlacement: end
enableVersioning: true
handle: payments
name: Payments
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/payments.twig
    uriFormat: payments
type: single
