defaultPlacement: end
enableVersioning: true
handle: periodontalTreatment
name: 'Periodontal Treatment'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/periodontal-treatment.twig
    uriFormat: periodontal-treatment
type: single
