defaultPlacement: end
enableVersioning: true
handle: rootCanalTherapy
name: 'Root Canal Therapy'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/root-canal-therapy.twig
    uriFormat: root-canal-therapy
type: single
