defaultPlacement: end
enableVersioning: true
handle: teethWhitening
name: 'Teeth Whitening'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/teeth-whitening.twig
    uriFormat: teeth-whitening
type: single
