defaultPlacement: end
enableVersioning: true
handle: veneers
name: Veneers
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/veneers.twig
    uriFormat: veneers
type: single
