defaultPlacement: end
enableVersioning: true
handle: whatToExpect
name: 'What to Expect'
propagationMethod: all
siteSettings:
  805ffc42-1721-4cde-a599-12ed2eee29ce: # gentledental
    enabledByDefault: true
    hasUrls: true
    template: _singles/what-to-expect.twig
    uriFormat: what-to-expect
type: single
